### ISSUE TITLE
When CLR reset hit Bus fault error 

### ISSUE THREAD

**Issue by ppjcheng** [NETMF/netmf-interpreter#83] opened 2015-04-22 14:47 UTC
When the CLR reset, the keil board will hit Bus Fault error at netif_set_ipAddr. 
The CLR reset after the VS Deployemnt, as it will hit the bus fault, then VS is no longer able to attached to the board for debugging. 
tcp_active_pcbs is all corrupted, that is why hit bus fault. the data inside the tcp_active_pcbs is bogus. Guess when CLR reset the tcp is not probably cleanup. If we look back the old lwip codes, we did add "MS_CHANGE" for purposely to do the cleanup. do we need that again?

**Comment by smaillet-ms** [comment] 2015-04-22 16:28
No we don't need that again. The MCBSTM32F400 port has a dedicated memory region for that and the reset code will clear and init the LWIP data. Unfortunately there is a known bug in the linker where the address of the initilzed data in ROM is fixed up incorrectly in the final link stage and we have to apply a manually determined offset, which unfortunately can change depending on other factors of the build. The source of the problem is in how the linker/compiler handles an uncompressed memory region listed in the scatter file. If the uncompressed region is preceeded by any compressed regions then the `Load$$xxx$$Base` value placed in the literal pool as a fixup will be incorrect. We've re-ordered the structure of the scatterfile and have been able to set that hacked offset to 0, but until we have a full fix in the next compiler linker release we'll need to keep a watch on that and potentially update the offset again. You can see the actual address of `Load$$ER_LWIP_OS$$RW$$Base` in the .MAP file and the AXFDUMP file will show the disassembly of `LwipReionInit()` to see what the linker fixup generated. Then update the constant `ArmLinkerLoadRegionOffsetHack` in `%SPOCLIENT%\Solutions\MCBSTM32F400\DeviceCode\Initialization\tinyhal.cpp` (~ line 411) Ideally that hack value is 0 but if the fixed up address seen in the AFXDUMP file doesn't match the actual address shown in the .MAP then it must be set to an offset to work around the bug.

**Closed** 2015-04-24 16:41 UTC
Labels: Discussion
