### ISSUE TITLE
Wrong exception for disposed socket

### ISSUE THREAD

**Issue by cpfister** [NETMF/netmf-interpreter#234] opened 2015-07-08 14:10 UTC
Using a disposed socket causes a SocketException, instead of an ObjectDisposed exception.

**Comment by ColinA-MSFT** [comment] 2015-07-22 21:42
It appears this works with the methods I've tried.  A scan of the entire class suggests all methods have a dispose check.  Can you provide a code sample that reproduces the issue?

**Comment by cpfister** [comment] 2015-07-23 07:44
It's a long time ago, but if I remember correctly there were indeed dispose checks. That wasn't the issue though. The issue was that they didn't always throw the correct type of exception as per the specification of the full .NET framework (SocketException where ObjectDisposedException would have been correct).

**Comment by ColinA-MSFT** [comment] 2015-07-23 15:32
It looks like that's been corrected.  All dispose checks are throwing ObjectDisposedException.  I'm going to close this out for now.  However, please don't hesitate to reopen this issue if you observe this again on 4.4.

**Closed by ColinA-MSFT** 2015-07-23 15:32 UTC
Labels: bug, No-Repro, PRI1 (must)
